### ISSUE TITLE
Add option to add total to the legend of the pie

### ISSUE THREAD

**Issue by metaodi** [IonicaBizau/node-cli-pie#12]
I'm currently working on a PR to add this feature, as I want to display the total for my project cabdriver, which uses cli-pie to display pie charts. Of course if you use percentage, the total is always 100%, so this is pretty useless. But in my case I use hours (as in working hours), each segment is the amount of time a person worked on each project, and finally I want to show how much they worked in total.

I was thinking of adding a new option called `display_total` (default: `false`) and maybe even another option called `total_label` (default: `Total`) to change the label in the legend.

WDYT?

**Comment by IonicaBizau** [comment]
That's cool! :sparkles: Was traveling these days. I looked at your PR. That's amazing!
