### ISSUE TITLE
Replace the legend square with a non-emoji

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/node-cli-pie#8]
/cc https://github.com/IonicaBizau/github-stats/issues/7

**Comment by adius** [comment]
s/◼/█/ or s/◼/▇/

**Comment by IonicaBizau** [comment]
Or maybe `▣`. 😄

**Comment by IonicaBizau** [comment]
@coltaemanuela Here is where the legend is being built:

https://github.com/IonicaBizau/node-cli-pie/blob/7edd070ba3ee19511d58710c3228cc2de54ba57e/lib/index.js#L224-L227

We have to replace that emoji with a similar character, which is *not* an emoji. :grin:
